config/routes.rb
Rails.application.routes.draw do
  resources :expressions
  resources :lessons
  resources :users
  get 'sessions/new'

  root 'index#index'

  get 'about', to: 'about#index', as: 'about'
  get 'services', to: 'services#index', as: 'services'
  get 'contact', to: 'contact#index', as: 'contact'

  get '/signup',  to: 'users#new', as: 'signup'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  get '/admin',  to: 'admin#index', as: 'admin'

  get 'expressions/:lesson_id/new', to: 'expressions#new', as: 'lesson_add_expression'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/expression.rb
class Expression < ApplicationRecord
  belongs_to :lesson
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  has_many :expression
end

app/models/user.rb
class User < ApplicationRecord
  
  before_save :encrypt_password
  
  validates_confirmation_of :password_hash
  validates_presence_of :password_hash, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  def self.authenticate(email, password)
    @email = email
    user = find_by_email(email)
    if user && user.password_hash == Digest::SHA2.hexdigest(user.password_salt + password)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password_hash.present?
      self.password_salt = SecureRandom.base64(8)
      self.password_hash = Digest::SHA2.hexdigest(self.password_salt + password_hash)
    end
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
    @lesson = Lesson.all
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]
  before_filter :admin_auth, only: [:index, :destroy, :new, :show, :new]

  # GET /lessons
  # GET /lessons.json
  def index
    @lessons = Lesson.all
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
  end

  # GET /lessons/1/edit
  def edit
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1
  # PATCH/PUT /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to @lesson, notice: 'Lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to lessons_url, notice: 'Lesson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lesson_params
      params.require(:lesson).permit(:name, :level, :content, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :create]
  before_filter :admin_auth, only: [:index, :destroy, :new, :show]
  #before_filter :validate_content, only: [:edit, :update]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:login, :email, :password_hash)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active?(controller_action_hash_or_array_or_string)
    controller = params[:controller]
    action = params[:action]

    controller_action_hash =
      case controller_action_hash_or_array_or_string
      when Array
        { controller => controller_action_hash_or_array_or_string }
      when String
        { controller_action_hash_or_array_or_string => nil }
      when Hash
        controller_action_hash_or_array_or_string
      else
        raise ArgumentError, "what are you even ..."
      end

    controller_action_hash = Hash[controller_action_hash.map{ |k, v| [k, [v || action].flatten] }]

    "active" if controller_action_hash.key?(controller) && controller_action_hash[controller].include?(action)
  end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/expressions_helper.rb
module ExpressionsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/_tabs.html.erb
<ul class="nav nav-stacked col-sm-2 ul-admin-panel">
  <li class="<%= active?('admin' => 'index') %> btn-admin-panel"><%= link_to "Panel administracyjny", admin_path %></li>
  <li class="<%= active?('lessons' => 'new') %> btn-admin-panel"><%= link_to "Dodaj lekcje", new_lesson_path %></li>
  <li class="<%= active?('lessons' => 'index') %> btn-admin-panel"><%= link_to "Pokaz lekcje", lessons_path %></li>
  <li class="<%= active?('users' => 'index') %> btn-admin-panel"><%= link_to "Pokaz uzytknownikow", users_path %></li>
</ul>

app/views/admin/index.html.erb
<%= render "admin/tabs" %>

app/views/index/index.html.erb
<div class="panel-custom">
  <section class="panel panel-default">
    <header class="panel-heading">
     <h5 class="panel-title">Lekcje Podstawowe</h5>
    </header>
     <ul class="lessons">
      <% @lesson.each do |l| %>
        <% if l.level == 1 %>
          <li><%= link_to l.name.to_s, lesson_path(l.id) %></li><hr class="lessons-panel">
        <% end %>
      <% end %>
    </ul>
    <header class="panel-heading">
     <h5 class="panel-title">Slowka</h5>
    </header>
     <ul class="lessons">
      <% @lesson.each do |l| %>
        <% if l.level == 2 %>
          <li><%= link_to l.name.to_s, lesson_path(l.id) %></li><hr class="lessons-panel">
        <% end %>
      <% end %>
    </ul>
    <header class="panel-heading">
     <h5 class="panel-title">Czasy</h5>
    </header>
     <ul class="lessons">
      <% @lesson.each do |l| %>
        <% if l.level == 3 %>
          <li><%= link_to l.name.to_s, lesson_path(l.id) %></li><hr class="lessons-panel">
        <% end %>
      <% end %>
    </ul>
    <header class="panel-heading">
     <h5 class="panel-title">Dialgi</h5>
    </header>
     <ul class="lessons">
      <% @lesson.each do |l| %>
        <% if l.level == 4 %>
          <li><%= link_to l.name.to_s, lesson_path(l.id) %></li><hr class="lessons-panel">
        <% end %>
      <% end %>
    </ul>
  </section>
</div>
<div class="section-main">
    <h3>Bezpłatny kurs języka angielskiego online</h3>
    <%= image_tag "City_of_London_banner", class: "london-banner" %>
    <p align="left">We współczesnym świecie znajomość języków obcych stała się koniecznością. Niemożliwy jest rozwój osobisty, awans zawodowy, nawiązywanie nowych kontaktów bez umiejętności posługiwania się językiem angielskim. Dlatego postanowiłam stworzyć ten kurs. Bezpłatny kurs języka angielskiego online przeznaczony jest zarówno dla osób dopiero rozpoczynających swoją przygodę z angielskim jak i dla tych, które już mają na tym polu jakieś osiągnięcia. W tworzeniu lekcji kieruję się swoim dwudziestoletnim doświadczeniem pedagogicznym opartym na kształceniu osób w różnym wieku, od małych dzieci do osób dorosłych. Mam nadzieję, że moja praca pozwoli na rozwinięcie u innych zamiłowania do nauki oraz przyda im się w życiu codziennym.</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nauka Angielskiego Online</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <script src='https://code.responsivevoice.org/responsivevoice.js'></script>
  </head>

  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= image_tag "britain_img", class: "nav-img" %>
            <%= link_to "Nauka Angielskiego", root_path, class: 'navbar-brand nav-font-text' %>
          </div>
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li><%= link_to "O nas", about_path %></li>
              <li><%= link_to "Serwisy", services_path %></li>
              <li><%= link_to "Kontakt", contact_path %></li>

              <% if current_user && current_user.user_group == 0 %>
                <li><%= link_to "Admin", admin_path %></li>
              <% end %>

            </ul>
            <div class="nav-login">
              <%= current_user ? link_to("Wyloguj", logout_path, method: :delete) + link_to(current_user.login.capitalize, edit_user_path(current_user)) : link_to('Rejestruj', signup_path) + link_to('Zaloguj', login_path) %></div>
          </div>
          <!-- /.navbar-collapse -->
      </div>
        <!-- /.container -->
    </nav>
    <div class="container container-main">
      <p id="notice"><%= notice %></p>
      <div><%= yield %></div>
    </div>


    <div class="footer navbar-fixed-bottom">
    <small>&#169; Mateusz Michalski</small>
      <div class="footer-links">
        | <%= link_to "Strona glowna", root_path %>
        | <%= link_to "O nas", about_path %>
        | <%= link_to "Serwisy", services_path %>
        | <%= link_to "Kontakt", contact_path %> | 
      </div>
    </div>
    <!-- jQuery Version 1.11.1 -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>