config/routes.rb
Rails.application.routes.draw do
  resources :expressions
  resources :lessons
  resources :users
  get 'sessions/new'

  root 'index#index'

  get 'about', to: 'about#index', as: 'about'
  get 'services', to: 'services#index', as: 'services'
  get 'contact', to: 'contact#index', as: 'contact'

  get '/signup',  to: 'users#new', as: 'signup'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  get '/admin',  to: 'admin#index', as: 'admin'

  get 'expressions/:lesson_id/new', to: 'expressions#new', as: 'lesson_add_expression'
end

app/models/expression.rb
class Expression < ApplicationRecord
  belongs_to :lesson
end

app/controllers/expressions_controller.rb
class ExpressionsController < ApplicationController
  before_action :set_expression, only: [:show, :edit, :update, :destroy]

  # GET /expressions
  # GET /expressions.json
  def index
    @expressions = Expression.all
  end

  # GET /expressions/1
  # GET /expressions/1.json
  def show
  end

  # GET /expressions/new
  def new
    @expression = Expression.new
  end

  # GET /expressions/1/edit
  def edit
  end

  # POST /expressions
  # POST /expressions.json
  def create
    @expression = Expression.new(expression_params)

    respond_to do |format|
      if @expression.save
        format.html { redirect_to @expression, notice: 'Expression was successfully created.' }
        format.json { render :show, status: :created, location: @expression }
      else
        format.html { render :new }
        format.json { render json: @expression.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expressions/1
  # PATCH/PUT /expressions/1.json
  def update
    respond_to do |format|
      if @expression.update(expression_params)
        format.html { redirect_to @expression, notice: 'Expression was successfully updated.' }
        format.json { render :show, status: :ok, location: @expression }
      else
        format.html { render :edit }
        format.json { render json: @expression.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expressions/1
  # DELETE /expressions/1.json
  def destroy
    @expression.destroy
    respond_to do |format|
      format.html { redirect_to expressions_url, notice: 'Expression was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expression
      @expression = Expression.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expression_params
      params.require(:expression).permit(:title, :english_sntnc, :polish_sntnc, :lesson_id, :audio_en, :audio_pl, :image, :premium)
    end
end

app/helpers/expressions_helper.rb
module ExpressionsHelper
end

app/views/expressions/_form.html.erb
<%= form_for(expression) do |f| %>
  <% if expression.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(expression.errors.count, "error") %> prohibited this expression from being saved:</h2>

      <ul>
      <% expression.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :zdanie_po_angielsku %>
    <%= f.text_area :english_sntnc %>
  </div>

  <div class="field">
    <%= f.label :zdanie_po_polsku %>
    <%= f.text_area :polish_sntnc %>
  </div>

  <div class="field">
    <%= f.label :lesson_id %>
    <%= f.text_field :lesson_id, value: params[:lesson_id] %>
  </div>

  <div class="field">
    <%= f.label :audio_en %>
    <%= f.text_field :audio_en %>
  </div>

  <div class="field">
    <%= f.label :audio_pl %>
    <%= f.text_field :audio_pl %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.text_field :image %>
  </div>

  <div class="field">
    <%= f.label :premium %>
    <%= f.check_box :premium %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/expressions/edit.html.erb
<h1>Editing Expression</h1>

<%= render 'form', expression: @expression %>

<%= link_to 'Pokaz zdanie', @expression %> |
<%= link_to 'Wroc', expressions_path %>

app/views/expressions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Expressions</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>English sntnc</th>
      <th>Polish sntnc</th>
      <th>Lesson</th>
      <th>Audio en</th>
      <th>Audio pl</th>
      <th>Image</th>
      <th>Premium</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @expressions.each do |expression| %>
      <tr>
        <td><%= expression.title %></td>
        <td><%= expression.english_sntnc %></td>
        <td><%= expression.polish_sntnc %></td>
        <td><%= expression.lesson.id.to_s %></td>
        <td><%= expression.audio_en %></td>
        <td><%= expression.audio_pl %></td>
        <td><%= expression.image %></td>
        <td><%= expression.premium %></td>
        <td><%= link_to 'Show', expression %></td>
        <td><%= link_to 'Edit', edit_expression_path(expression) %></td>
        <td><%= link_to 'Destroy', expression, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Expression', new_expression_path %>

app/views/expressions/new.html.erb
<h1>New Expression</h1>

<%= render 'form', expression: @expression %>

<%= link_to 'Wroc', expressions_path %>

app/views/expressions/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @expression.title %>
</p>

<p>
  <strong>English sntnc:</strong>
  <%= @expression.english_sntnc %>
</p>

<p>
  <strong>Polish sntnc:</strong>
  <%= @expression.polish_sntnc %>
</p>

<p>
  <strong>Lesson:</strong>
  <%= @expression.lesson.id %>
</p>

<p>
  <strong>Audio en:</strong>
  <%= @expression.audio_en %>
</p>

<p>
  <strong>Audio pl:</strong>
  <%= @expression.audio_pl %>
</p>

<p>
  <strong>Image:</strong>
  <%= @expression.image %>
</p>

<p>
  <strong>Premium:</strong>
  <%= @expression.premium %>
</p>

<%= link_to 'Edytuj', edit_expression_path(@expression) %> |
<%= link_to 'Wroc', expressions_path %>