config/routes.rb
Rails.application.routes.draw do
  resources :expressions
  resources :lessons
  resources :users
  get 'sessions/new'

  root 'index#index'

  get 'about', to: 'about#index', as: 'about'
  get 'services', to: 'services#index', as: 'services'
  get 'contact', to: 'contact#index', as: 'contact'

  get '/signup',  to: 'users#new', as: 'signup'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  get '/admin',  to: 'admin#index', as: 'admin'

  get 'expressions/:lesson_id/new', to: 'expressions#new', as: 'lesson_add_expression'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/expression.rb
class Expression < ApplicationRecord
  belongs_to :lesson
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  has_many :expression
end

app/models/user.rb
class User < ApplicationRecord
  
  before_save :encrypt_password
  
  validates_confirmation_of :password_hash
  validates_presence_of :password_hash, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  def self.authenticate(email, password)
    @email = email
    user = find_by_email(email)
    if user && user.password_hash == Digest::SHA2.hexdigest(user.password_salt + password)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password_hash.present?
      self.password_salt = SecureRandom.base64(8)
      self.password_hash = Digest::SHA2.hexdigest(self.password_salt + password_hash)
    end
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def admin_auth
    unless current_user.nil? || current_user.user_group.to_s == '0'
      redirect_to root_path
    end
  end

  def validate_content
    unless current_user.id.to_s == params[:id].to_s
      flash[:notice] = "Mozesz edytowac tylko swojego uzytkownika"
      redirect_to root_path
    end
  end

  def audio_path(source, options = {})
    path_to_asset(source, {type: :audio}.merge!(options))
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
    @lesson = Lesson.all
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]
  before_filter :admin_auth, only: [:index, :destroy, :new, :show, :new]

  # GET /lessons
  # GET /lessons.json
  def index
    @lessons = Lesson.all
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
  end

  # GET /lessons/1/edit
  def edit
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1
  # PATCH/PUT /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to @lesson, notice: 'Lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to lessons_url, notice: 'Lesson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lesson_params
      params.require(:lesson).permit(:name, :level, :content, :image)
    end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    #raise params.inspect
    user = User.authenticate(params[:session][:email], params[:session][:password])
    if user
      session[:user_id] = user.id
      redirect_to root_path, :notice => "Successfully logged in!"
    else
      @notice = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :create]
  before_filter :admin_auth, only: [:index, :destroy, :new, :show]
  #before_filter :validate_content, only: [:edit, :update]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:login, :email, :password_hash)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active?(controller_action_hash_or_array_or_string)
    controller = params[:controller]
    action = params[:action]

    controller_action_hash =
      case controller_action_hash_or_array_or_string
      when Array
        { controller => controller_action_hash_or_array_or_string }
      when String
        { controller_action_hash_or_array_or_string => nil }
      when Hash
        controller_action_hash_or_array_or_string
      else
        raise ArgumentError, "what are you even ..."
      end

    controller_action_hash = Hash[controller_action_hash.map{ |k, v| [k, [v || action].flatten] }]

    "active" if controller_action_hash.key?(controller) && controller_action_hash[controller].include?(action)
  end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/expressions_helper.rb
module ExpressionsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/lessons/_form.html.erb
<%= form_for lesson do |f| %>
  <div class="field">
    <%= f.label :nazwa %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :poziom %>
    <%= f.text_field :level %>
  </div>

  <div class="field">
    <%= f.label :krotki_opis %>
    <%= f.text_area :content, size: "30x10" %>
  </div>

  <div class="field">
    <%= f.label :obraz_url %>
    <%= f.text_field :image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
  <div class="add-expression-container">
    <% lesson.expression.each do |ex| %>
      <%= form_for ex do |e| %>
        <div class="field">
          <%= e.label :tytul %>
          <%= e.text_field :title %>
        </div>

        <div class="field">
          <%= e.label :zdanie_po_angielsku %>
          <%= e.text_area :english_sntnc, size: "30x10" %>
        </div>

        <div class="field">
          <%= e.label :zdanie_po_polsku %>
          <%= e.text_area :polish_sntnc, size: "30x10" %>
        </div>
        
        <div class="field">
          <%= e.label :obraz_url, "Wrzuc plik glosowy po angielsku" %>
          <%= e.file_field :audio_en %>
        </div>

        <div class="field">
          <%= e.label :obraz_url %>
          <%= e.text_field :image %>
        </div>

        <div class="actions">
          <%= e.submit %>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/lessons/_tabs.html.erb
<ul class="nav nav-stacked col-sm-2 ul-admin-panel">
  <li class="<%= active?('admin' => 'index') %> btn-admin-panel"><%= link_to "Panel administracyjny", admin_path %></li>
  <li class="<%= active?('lessons' => 'new') %> btn-admin-panel"><%= link_to "Dodaj lekcje", new_lesson_path %></li>
  <li class="<%= active?('lessons' => 'index') %> btn-admin-panel"><%= link_to "Pokaz lekcje", lessons_path %></li>
  <li class="<%= active?('lessons' => 'edit') %> btn-admin-panel"><%= link_to "Edytuj lekcje", '#' %></li>
  <li class="<%= active?('users' => 'index') %> btn-admin-panel"><%= link_to "Pokaz uzytknownikow", users_path %></li>
</ul>

app/views/lessons/edit.html.erb
<%= render 'tabs' %>
<div class="add-lesson-container">
  <h1>Editing Lesson</h1>
  <br>
  <%= link_to 'Pokaz', @lesson %> |
  <%= link_to 'Wroc', lessons_path %>

  <%= render 'form', lesson: @lesson %>
  <br>
  <%= link_to 'Dodaj zdanie', lesson_add_expression_path(@lesson.id) %>
</div>

app/views/lessons/index.html.erb
<%= render 'admin/tabs' %>
<p id="notice"><%= notice %></p>

<h1>Wszystkie Lekcje</h1><br>

<table>
  <thead>
    <tr>
      <th>Nazwa</th>
      <th>&nbsp;Poziom</th>
      <th>&nbsp;Krotki Opis</th>
      <th>&nbsp;Zdjecie URL</th>
      <th>&nbsp;Kategoria</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lessons.each do |lesson| %>
      <tr>
        <td><%= lesson.name %></td>
        <td><%= lesson.level %></td>
        <td><%= lesson.content %></td>
        <td><%= lesson.image %></td>
        <% case lesson.level %>
          <% when 1 %>
            <td>Lekce podstawowe</td>
          <% when 2 %>
            <td>Slowka</td>
          <% when 3 %>
            <td>Dialogi</td>
          <% else %>
            <td>N/A</td>
        <% end %>
        <td><%= link_to 'Pokaz', lesson %></td>
        <td><%= link_to 'Edytuj', edit_lesson_path(lesson) %></td>
        <td><%= link_to 'Usun', lesson, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nowa lekcja', new_lesson_path %>

app/views/lessons/new.html.erb
<%= render 'admin/tabs' %>
<div class="add-lesson-container"><h1>Nowa lekcja</h1>

<%= render 'form', lesson: @lesson %>

<%= link_to 'Wroc', lessons_path %>
</div>

app/views/lessons/show.html.erb
<p id="notice"><%= notice %></p>

<p align="center">
  <strong><%= @lesson.name %></strong><%= ' (' + @lesson.content + ')' unless @lesson.content.empty? %>
  <br>Level: <%= @lesson.level %>

<table class="lesson-table">
<tbody>
  <% flag = false %>
  <% @lesson.expression.each_with_index do |e, i| %>
    <% flag ^= true %>
    <% unless !flag %>
      <tr>
    <% end %>
    <td class="lesson-table-td">
      <div class="sentence expression-tag" id="sentence_<%= i %>" data-id="<%= i %>" flag="0"><%= e.english_sntnc.html_safe %></div><div class="expression-tag"><input onclick='responsiveVoice.speak("<%= e.english_sntnc.to_s %>");' type='button' value='🔊' /></div>
      <div id="sentence_en_<%= i %>" style="visibility: hidden"><%= e.english_sntnc.html_safe %></div>
      <div id="sentence_pl_<%= i %>" style="visibility: hidden"><%= e.polish_sntnc.html_safe %></div>
    </td>
    <% unless flag %>
      </tr>
    <% end %>
  <% end %>
</tbody>
</table>
</p>
<% if current_user && current_user.user_group == 0 %>
  <div class="admin-controlers">
    <%= link_to 'Edytuj', edit_lesson_path(@lesson) %> |
    <%= link_to 'Wroc', lessons_path %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <%= f.label :login %><%= f.text_field :login, class: "sign-up-field" %><br />
  <%= f.label :email, "Adres email" %>
  <%= f.text_field :email, class: "shortInput" %> <br />
  <%= f.label :haslo %>
  <%= f.password_field :password_hash, class: "shortInput" %> <br />
  <%= f.label :password_confirmation, "Potwierdz haslo" %>
  <%= f.password_field :password_confirmation, class: "shortInput" %>
  <% if current_user && current_user.user_group == 0 %>
    <%= f.label :user_group, "Grupa uzytkownika" %>
    <%= f.text_field :user_group, class: "shortInput" %> <br />
  <% end %>

  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="section-main">
  <h1>Editing User</h1>

  <%= render 'form', user: @user %>

  <% if current_user && current_user.user_group == 0 %>
    <%= link_to 'Pokaz', @user %> |
    <%= link_to 'Wroc', users_path %>
  <% end %>
</div>

app/views/users/index.html.erb
<%= render 'admin/tabs' %>
<div class="section-main">
  <p id="notice"><%= notice %></p>

  <h1>Wszyscy Uzytkownicy</h1><br>

  <table class="section-main">
    <thead>
      <tr>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><b><%= user.login %></b></td>
          <td><%= link_to "Show", user %></td>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br><br><br>
  <p><%= link_to 'Nowy uzytkownik', new_user_path %></p>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="section-main">
  <%= link_to 'Edytuj', edit_user_path(@user) %> |
  <%= link_to 'Wroc', users_path %>
</div>